### PR TITLE
Added more specific stuff to the Unity project installation instructions.

### PR DESCRIPTION
**Pull request by Hassunaama**

### CODE REVIEW

**Comment by FoxSylv1** [comment]
Yeah! I agree that the download instructions needed to be a bit better I kinda wrote them sleep deprived a bit >w<

Also just as an FYI, there's this cool feature in GitHub called "draft PR", where you can open the PR, but still communicate that you're working on the specifics so an unfinished result doesn't get merged! I just noticed that you've made changes since opening the PR, and I wasn't sure if you were aware of the feature ^w^. I'll let you mark it however you choose (if you don't have perms to do so, just lemme know plz :P)

**Comment by Hassunaama** [comment]
Oh, yeah. I did not remember about the draft pull requests, I had seen the button some time ago, and forgot about it since.

**Comment by FoxSylv1** [comment]
More on a PR-focused note, github also has a feature that allows you to download a repository directly from the website (Code -> Download ZIP), so Git isn't _required_ persay, but I do agree that a link to Git is a good idea for those inclined.

Also since I didn't make it clear in the original instructions, the exact Unity Editor version I used was 2021.3.16f1 so yay specificity!

I really like how the better instructions are turning out btw ^w^

**Comment by Hassunaama** [comment]
> More on a PR-focused note, github also has a feature that allows you to download a repository directly from the website (Code -> Download ZIP), so Git isn't _required_ persay, but I do agree that a link to Git is a good idea for those inclined.
> 
> Also since I didn't make it clear in the original instructions, the exact Unity Editor version I used was 2021.3.16f1 so yay specificity!
> 
> I really like how the better instructions are turning out btw ^w^

I know that you can download the zip file from github, but I thinked that it would be easier for Linux users to use git, and having git is also otherwise a great thing to have. But if you think the zip notice should be added to the readme, then ok.

**Comment by FoxSylv1** [comment]
This has been open for a bit is it alright if I just merge it?

**Comment by Hassunaama** [comment]
Sure, There is nothing I want to add.

**Pull request merged**
